[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
prop_pool = "9DzBp7dwMGVBWY6oL3yH59R8YsYFbqnybACg6SwzAwTQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
