name: prop-pool

services:
  surfpool:
    build: 
      context: .
      dockerfile: Dockerfile.Surfpool
    ports:
      - "8899:8899"
      - "8900:8900"
      - "8080:8080"
    env_file:
      - .env
    networks:
      - prop-pool-network

networks:
  prop-pool-network:
    driver: bridge
